// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisualStudioChatExtension.Configuration
{
    internal sealed partial class Vsix
    {
        public const string Id = "VisualStudioChatExtension.529683bd-456f-4ca4-a1e8-93c9159cbf08";
        public const string Name = "VisualStudioChatExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tiago Pala";
        public const string Tags = "";
    }
}
