// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisualStudioChatExtension.Configuration
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VisualStudioChatExtensionString = "00e4f3d7-1e3a-4cd3-b039-93b2242dbb04";
        public static Guid VisualStudioChatExtension = new Guid(VisualStudioChatExtensionString);

        public const string guidVisualStudioChatExtensionPackageCmdSetString = "9aa983d3-c07c-4f94-8451-e788ffb1e16c";
        public static Guid guidVisualStudioChatExtensionPackageCmdSet = new Guid(guidVisualStudioChatExtensionPackageCmdSetString);

        public const string guidImagesString = "e318b7bf-eab9-40d7-89bb-2c12f483a9d5";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int cmdidChatToolWindowCommand = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}